import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";
import ReduxProvider from "./../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-full">
        <Header />
        <ReduxProvider>{children}</ReduxProvider>
        <div className="m-10 text-center mt-20 lg:mt-60">Mahdi Akbari</div>
      </body>
    </html>
  );
}
